### ISSUE TITLE
[TEMPLATES] Create Issue Templates for Claude Code Requests

### ISSUE THREAD

**Issue by raegAI** [raegAI/hyperliquid-python-sdk#9]
@claude Please create GitHub issue templates in `.github/ISSUE_TEMPLATE/` directory to standardize Claude Code automation requests:

**Required Templates:**

1. **`.github/ISSUE_TEMPLATE/claude_feature.md`** - For feature implementations
2. **`.github/ISSUE_TEMPLATE/claude_bug_fix.md`** - For bug fixes
3. **`.github/ISSUE_TEMPLATE/claude_refactor.md`** - For code refactoring
4. **`.github/ISSUE_TEMPLATE/claude_documentation.md`** - For documentation updates
5. **`.github/ISSUE_TEMPLATE/claude_testing.md`** - For testing improvements

**Template Structure (each should include):**
```yaml
---
name: [Template Name]
about: [Description of when to use this template]
title: '[TYPE] '
labels: ['claude-automation', '[specific-type]']
assignees: ''
---

@claude [Specific request format for this type]

**Requirements:**
- [ ] Requirement 1
- [ ] Requirement 2

**Acceptance Criteria:**
- [ ] Success criteria 1
- [ ] Success criteria 2

**Technical Details:**
- Files to modify: 
- Dependencies to consider:
- Backwards compatibility: Yes/No

**Testing Requirements:**
- [ ] Unit tests required
- [ ] Integration tests required
- [ ] Example validation required

**Documentation Updates:**
- [ ] Code documentation (docstrings)
- [ ] README updates
- [ ] Example updates

**Additional Context:**
[Any relevant background information]
```

**Customization per Template:**
- **Feature**: Focus on new functionality, API additions, performance improvements
- **Bug Fix**: Include reproduction steps, expected vs actual behavior, error logs
- **Refactor**: Specify code quality goals, performance targets, maintainability improvements
- **Documentation**: Define documentation scope, audience, format requirements
- **Testing**: Specify test coverage goals, test types, performance benchmarks

**Integration Features:**
- Auto-label with appropriate automation tags
- Include reference to CLAUDE.md configuration
- Provide guidance on scope and complexity
- Include links to relevant examples or documentation

**Quality Assurance:**
- Templates should guide users to provide sufficient detail
- Include prompts for security considerations where applicable
- Encourage backwards compatibility considerations
- Reference existing patterns and conventions

Please create comprehensive templates that will help users structure effective Claude Code requests and ensure consistent automation pipeline execution.
